// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7NZ7P12e4g9dVFZwiYNR1ZVu2PBoh3A',
    appId: '1:975603123709:web:4bdd4061e4acabaa1cc594',
    messagingSenderId: '975603123709',
    projectId: 'flashcard-project-7a3c7',
    authDomain: 'flashcard-project-7a3c7.firebaseapp.com',
    storageBucket: 'flashcard-project-7a3c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHAcI4_Rbruhw5amNNaUEkMX67niTFVU',
    appId: '1:975603123709:android:8e30525f9db9fc061cc594',
    messagingSenderId: '975603123709',
    projectId: 'flashcard-project-7a3c7',
    storageBucket: 'flashcard-project-7a3c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CF8rF0eDlSE_S1o9PtgvIS0vKnrVams',
    appId: '1:975603123709:ios:ba7c96d9530e21b21cc594',
    messagingSenderId: '975603123709',
    projectId: 'flashcard-project-7a3c7',
    storageBucket: 'flashcard-project-7a3c7.firebasestorage.app',
    iosBundleId: 'com.example.quizFlashcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_CF8rF0eDlSE_S1o9PtgvIS0vKnrVams',
    appId: '1:975603123709:ios:ba7c96d9530e21b21cc594',
    messagingSenderId: '975603123709',
    projectId: 'flashcard-project-7a3c7',
    storageBucket: 'flashcard-project-7a3c7.firebasestorage.app',
    iosBundleId: 'com.example.quizFlashcard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI7NZ7P12e4g9dVFZwiYNR1ZVu2PBoh3A',
    appId: '1:975603123709:web:33a35663a139cdf61cc594',
    messagingSenderId: '975603123709',
    projectId: 'flashcard-project-7a3c7',
    authDomain: 'flashcard-project-7a3c7.firebaseapp.com',
    storageBucket: 'flashcard-project-7a3c7.firebasestorage.app',
  );

}